### Parameters related to acoustic features

# f0 

use_existing_f0: false                 # do not perform pitch tracking if .f0 file exists
pitch_tracker: inst_freq               # inst_freq (our algorithm) or REAPER (from google)
min_f0:        50
max_f0:        400
voicing_threshold:  50              # from 0 (all voiced) to 100 (no voicing)
interpolation_method: true_envelope # fill unvoiced sections; "linear", "pchip" or "true_envelope"

# energy

# subband for energy calculation (in hz)
energy_band_min: 400
energy_band_max: 5000
energy_calculation_method: rms            # 'rms', 'hilbert' or 'true_envelope'  (root mean square, hilbert envelope, or true envelope -inspired method)
smooth_energy: True                       # smoothing reduces the effect of voicing related variation in energy contour


# duration

acoustic_estimation: False               # estimate speech rate from signal using wavelet transform of energy 
delta_duration: False                    # use differential duration signal, useful for boundary detection
duration_tiers: [segments, words]
silence_symbols: ["#", "!pau", "<s>", "pau", "!sil", "sil", "", " ","<p>", "<p:>", "." ,",","?"]

### combining features

feature_combination: product       # sum or product
detrend: True                  # detrend can be used to remove typical downdrift during utterance, mainly produces more balanced looking scalograms

#  feature weights

weights:
   f0:       1.0
   energy:   1.0
   duration: 0.5



###  Labels

# adjust these to your annotation scheme
annotation_tier: words  



### Wavelet transform


mother_wavelet: mexican_hat    # mexican_hat, morlet or paul
period:         3              # applies to morlet and paul wavelets (periods 2 - 5 are reasonable)

scale_distance: 0.25         # distance between adjacent scales in octaves, (0.25 means 4 scales per octave)
num_scales: 40               # number of wavelet scales          

magnitude: False             # for purposes other than prosodic event annotation,
                             # examinining wavelet magnitude might be useful (complex wavelets Morlet or Paul should be used)


# lines of maximum amplitude, defined as octaves below and above
# the measured unit scale 

prom_loma_start:     -3  # -3 meaning three octaves below unit scale
prom_loma_end:        0  #  0
boundary_loma_start: -2
boundary_loma_end:    1  # one octave higher than unit scale



