# SCM part
branches:
  only:
    - master

# System part
matrix:
  include:
    - os: linux

language: python

python:
  - "3.6"
  - "3.6-dev"  # 3.6 development branch
  # - "3.7-dev"  # 3.7 development branch

cache: pip

install:
  - pip install -e .

script:
  - bash test/run_test.sh
