# SCM part
branches:
  only:
    - master

# System part
language: python

os:
  - linux
  # - osx
  # - windows

python:
  - "3.6"

  # Windows
cache: pip


before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update          ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install pyqt5 ; fi


install:
  - pip install -e .

script:
  - bash test/run_test.sh
